# -------------------ğŸ‘‡ ä¸‹é¢æ˜¯ server ç›¸å…³çš„é…ç½® -----------------
home:
    minio:
        access_key: ponponon
        secret_key: ponponon
        end_point: 192.168.31.245:9000
        bucket: whoisface

work:
    minio:
        access_key: ponponon
        secret_key: ponponon
        end_point: 192.168.31.245:9000
        bucket: whoisface